In [ ]:
import numpy as np
num_string = np.array(['5.76','-17.6','85'],dtype = np.string_)
num = num_string.astype(float)
print(num)
int_num = num.astype(np.int32)
print(int_num)

[  5.76 -17.6   85.  ]
[  5 -17  85]

In [ ]:
array1 = np.arange(12)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [ ]:
array2 = array1.reshape(3,4)
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [ ]:
array3 = array2.reshape(4,3)
print(array3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

In [ ]:
array2 = array1.reshape(3,4)
print(array2)
print(array2.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [ ]:
array3 = array2.reshape(4,3)
print(array3)
print(array2.ravel())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [7]:
import pandas as pd
import numpy as np

data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
r = np.array(['r1','r2'])
c = np.array(['c1','c2','c3'])
df = pd.DataFrame(data=data,
                  index=r,
                  columns=c)
df

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [9]:
my_df = pd.DataFrame(data=[4,5,6,7],index=range(0,4), columns=['A'])
print(pd.DataFrame(my_df))

   A
0  4
1  5
2  6
3  7

In [10]:
my_series = pd.Series({"United Kingdom":"London","India":"New Delhi",
                       "United States":"Washington","Belgium":"Brussels"})
print(pd.DataFrame(my_series))

                         0
United Kingdom      London
India            New Delhi
United States   Washington
Belgium           Brussels

In [13]:
import pandas as pd
import numpy as np
from numpy.random import randn
np.random.seed(101) # กำหนดค่าให้มันคงที่ในกรณีนี้เป็น 101

arr = randn(5,4)

df = pd.DataFrame(arr,index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [15]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [16]:
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [18]:
df['new2'] = df['W'].add(df['Y'])
df

          W         X         Y         Z       new      new2
A  2.706850  0.628133  0.907969  0.503826  3.614819  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762  2.796762

In [19]:
df2 = df.drop('new',axis=1)
df2

          W         X         Y         Z      new2
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [20]:
df.drop('new',axis=1,inplace=True)
df

          W         X         Y         Z      new2
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [21]:
df.drop('E',axis=0)

          W         X         Y         Z      new2
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542

In [50]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Sales':[200,120,340,124,243,350 ]}
df = pd.DataFrame(data)
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [52]:
by_comp = df.groupby('Company')
by_comp

In [53]:
by_comp.mean()

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [54]:
df.groupby('Company').mean()

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [26]:
import pandas as pd
import numpy as np

long_series = pd.Series(np.random.randn(1000))

long_series.head()

0    0.302665
1    1.693723
2   -1.706086
3   -1.159119
4   -0.134841
dtype: float64

In [27]:
long_series.tail(3)

997   -0.824182
998   -0.553474
999    0.368730
dtype: float64

In [28]:
import pandas as pd
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']},
                   index=[0,1,2,3])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [29]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7']},
                   index=[4,5,6,7])
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [33]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C':['C8','C9','C10','C11'],
                    'D':['D8','D9','D10','D11']},
                   index=[0,1,2,3])
df3

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [34]:
pd.concat([df1,df2,df3])

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
4   A4   B4   C4   D4
5   A5   B5   C5   D5
6   A6   B6   C6   D6
7   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [35]:
pd.concat([df1,df2,df3],axis=1)

     A    B    C    D    A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN   A8   B8   C8   D8
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN   A9   B9   C9   D9
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN  A10  B10  C10  D10
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN  A11  B11  C11  D11
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN

In [37]:
left = pd.DataFrame({'key':['K0','K1','K2','K3'],
                     'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']})
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [38]:
right = pd.DataFrame({'key':['K0','K1','K2','K3'],
                     'A':['C0','C1','C2','C3'],
                     'B':['D0','D1','D2','D3']})
right

  key   A   B
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [39]:
pd.merge(left,right,how='inner',on='key')

  key A_x B_x A_y B_y
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [45]:
raw_data = {'first_name':['Jason',np.nan,'Tina','Jake','Amy'],
            'last_name':['Miller',np.nan,'Ali','Milner','Cooze'],
            'age':[42,np.nan,36,24,73],
            'sex':['m',np.nan,'f','m','f'],
            'preTestScore':[4,np.nan,np.nan,2,3],
            'postTestScore':[25, np.nan ,np.nan,62,70]}
df = pd.DataFrame(raw_data,columns = ['first_name','last_name','age',
                                      'sex','preTestScore','postTestScore'])
df

  first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [46]:
df_no_missing = df.dropna()
df_no_missing

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [47]:
df_cleaned = df.dropna(how='all')
df_cleaned

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [48]:
df.fillna(0)

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
1          0         0   0.0   0           0.0            0.0
2       Tina       Ali  36.0   f           0.0            0.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [49]:
df['preTestScore'].fillna(df['preTestScore'].mean(),inplace=True)
df

  first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           3.0            NaN
2       Tina       Ali  36.0    f           3.0            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0